# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x0eg6_cli_utility\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n\tStateData\x12\n\n\x02id\x18\x01 \x01(\x05\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04text\x18\x03 \x01(\t\"\"\n\x04\x42\x65\x61t\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\r\"e\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x32\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\tB\x0c\n\n_timestamp\" \n\x08Response\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2\xb0\x04\n\x10RequiredCommands\x12\x37\n\x05\x42\x65gin\x12\x14.g6_cli_utility.Data\x1a\x18.g6_cli_utility.Response\x12\x35\n\x03\x45nd\x12\x14.g6_cli_utility.Data\x1a\x18.g6_cli_utility.Response\x12;\n\tAutopilot\x12\x14.g6_cli_utility.Data\x1a\x18.g6_cli_utility.Response\x12\x37\n\x05Reset\x12\x14.g6_cli_utility.Data\x1a\x18.g6_cli_utility.Response\x12\x37\n\x05\x42rake\x12\x14.g6_cli_utility.Data\x1a\x18.g6_cli_utility.Response\x12<\n\nAccelerate\x12\x14.g6_cli_utility.Data\x1a\x18.g6_cli_utility.Response\x12<\n\nDecelerate\x12\x14.g6_cli_utility.Data\x1a\x18.g6_cli_utility.Response\x12;\n\tHeartBeat\x12\x14.g6_cli_utility.Beat\x1a\x18.g6_cli_utility.Response\x12\x44\n\rSendStateData\x12\x19.g6_cli_utility.StateData\x1a\x18.g6_cli_utility.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATEDATA']._serialized_start=67
  _globals['_STATEDATA']._serialized_end=151
  _globals['_BEAT']._serialized_start=153
  _globals['_BEAT']._serialized_end=187
  _globals['_DATA']._serialized_start=189
  _globals['_DATA']._serialized_end=290
  _globals['_RESPONSE']._serialized_start=292
  _globals['_RESPONSE']._serialized_end=324
  _globals['_REQUIREDCOMMANDS']._serialized_start=327
  _globals['_REQUIREDCOMMANDS']._serialized_end=887
# @@protoc_insertion_point(module_scope)
